void receive_commands();
// char* shouldRealloc(int* curSize, int position, char* buf);
// unsigned long hash(unsigned char *str);
char** commands();
char* addWord(char*);
char *trimwhitespace(char *);
char** sliceWords(char *, int *);
// int shellCommands(char **, int);
void checkErr(int);
int wordSize(char **);
char *buildstring(char **foo, int words);
void freeInput(char **input);
